# Generated by Django 6.0 on 2026-05-02 15:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('TodaySchedule_medication', '0002_schedule_date_schedule_is_taken_schedule_taken_at'),
        ('newRequest_activePrescription_medication', '0004_rename_user_prescriptionrequest_patient_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('taken_with_food', 'Taken with food'), ('taken_solo', 'Taken solo'), ('taken', 'Taken'), ('missed', 'Missed'), ('delyed', 'Delayed'), ('yesterday', 'Yesterday'), ('other', 'Other')], max_length=30)),
                ('clinical_observation', models.TextField(blank=True, null=True)),
                ('symptoms', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='newRequest_activePrescription_medication.prescriptionrequest')),
                ('today_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='TodaySchedule_medication.schedule')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='update_log', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
