# Generated by Django 5.2.14 on 2026-05-10 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription_management', '0002_prescription_document_type_prescription_findings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='document_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
