# Generated by Django 6.0 on 2026-05-03 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editProfile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='editprofile',
            name='emergency_contact_number',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='editprofile',
            name='emergency_contact_name',
            field=models.CharField(max_length=255),
        ),
    ]
