# Generated by Django 6.0 on 2026-05-05 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editProfile', '0002_editprofile_emergency_contact_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editprofile',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='editprofile',
            name='emergency_contact_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
