# Generated by Django 6.0 on 2026-04-09 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Dr_personalInfo", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DoctorProfessionalInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("doctor_employee_id", models.CharField(max_length=50)),
                ("department", models.CharField(max_length=100)),
                ("specialization", models.CharField(max_length=100)),
                ("qualification", models.CharField(max_length=200)),
                ("years_of_experience", models.PositiveIntegerField()),
                ("medical_license_number", models.CharField(max_length=100)),
                ("medical_council", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "doctor",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="professional_info",
                        to="Dr_personalInfo.doctorpersonalinfo",
                    ),
                ),
            ],
        ),
    ]
