# Generated by Django 6.0 on 2026-05-07 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SymptomChecker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition_name', models.CharField(max_length=200)),
                ('confidence_score', models.DecimalField(decimal_places=1, max_digits=5)),
                ('report_snapshot', models.JSONField()),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_reports', to='SymptomChecker.patient')),
            ],
        ),
    ]
