# Generated by Django 6.0 on 2026-05-07 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SymptomChecker', '0002_savedreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='SymptomAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_symptoms', models.JSONField(default=list)),
                ('severity', models.PositiveSmallIntegerField()),
                ('environmental_triggers', models.JSONField(default=list)),
                ('additional_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='SymptomChecker.patient')),
            ],
        ),
    ]
