# Generated by Django 6.0 on 2026-05-07 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SymptomChecker', '0003_symptomauditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicationDose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication_name', models.CharField(max_length=200)),
                ('instructions', models.TextField(blank=True)),
                ('time_taken', models.TimeField()),
                ('date_taken', models.DateField()),
                ('observation_notes', models.TextField(blank=True)),
                ('confirmed_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication_doses', to='SymptomChecker.patient')),
            ],
        ),
    ]
