# Generated by Django 5.2.14 on 2026-05-11 18:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnostic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_part', models.CharField(max_length=100)),
                ('sub_region', models.CharField(max_length=100)),
                ('symptoms', models.JSONField()),
                ('duration', models.CharField(max_length=100)),
                ('severity', models.CharField(max_length=50)),
                ('possible_diseases', models.JSONField()),
                ('recommendations', models.JSONField()),
                ('precautions', models.JSONField()),
                ('consultation_advice', models.TextField()),
                ('confidence_score', models.FloatField()),
                ('ai_response', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnostics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
