# Generated by Django 6.0 on 2026-04-29 17:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication_name', models.CharField(max_length=100)),
                ('dosage', models.CharField(max_length=100)),
                ('frequency', models.CharField(choices=[('Once Daily', 'Once Daily'), ('Twice Daily', 'Twice Daily'), ('Thrice Daily', 'Thrice Daily'), ('Every 4 Hours', 'Every 4 Hours'), ('Every 6 Hours', 'Every 6 Hours'), ('Every 8 Hours', 'Every 8 Hours'), ('Every 12 Hours', 'Every 12 Hours'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly')], max_length=20)),
                ('time', models.TimeField()),
                ('routine_type', models.CharField(choices=[('Routine', 'Routine'), ('As Needed', 'As Needed')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
