# Generated by Django 6.0 on 2026-05-05 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_appointment_rejection_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='patient_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
