# Generated by Django 6.0 on 2026-05-09 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_alter_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='patient_gender',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
