# Generated by Django 5.2.14 on 2026-05-12 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_appointment_patient_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='patient_blood_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient_disease',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient_heart_rate',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient_photo',
            field=models.ImageField(blank=True, null=True, upload_to='patient_photos/'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient_weight',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('booked', 'Booked'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected'), ('outpatient', 'OutPatient')], default='pending', max_length=20),
        ),
    ]
