# Generated by Django 6.0 on 2026-05-02 20:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('clinician_id', models.CharField(max_length=100, unique=True)),
                ('language', models.CharField(default='English (United Kingdom)', max_length=100)),
                ('timezone', models.CharField(default='GMT +05:30 (Mumbai, India)', max_length=100)),
                ('automatic_updates', models.BooleanField(default=True)),
                ('two_factor_enabled', models.BooleanField(default=False)),
                ('data_sharing', models.BooleanField(default=False)),
                ('profile_visibility', models.CharField(choices=[('internal_only', 'Internal Only'), ('public', 'Public'), ('private', 'Private')], default='internal_only', max_length=50)),
                ('hipaa_logs_enabled', models.BooleanField(default=True)),
                ('account_deactivated', models.BooleanField(default=False)),
                ('request_data_deletion', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
