# Generated by Django 6.0 on 2026-05-03 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_setting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountsettings',
            name='clinician_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='accountsettings',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='accountsettings',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='accountsettings',
            name='profile_visibility',
            field=models.CharField(default='internal_only', max_length=50),
        ),
    ]
