# Generated by Django 6.0 on 2026-04-17 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorPersonalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('mobile_number', models.CharField(max_length=15)),
                ('alternate_number', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('incomplete', 'Incomplete'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='incomplete', max_length=15)),
                ('rejected_file', models.FileField(blank=True, null=True, upload_to='rejected/')),
                ('rejected_reason', models.CharField(blank=True, choices=[('invalid_docs', 'Invalid Documents'), ('missing_info', 'Missing Information'), ('license_issue', 'License Issue'), ('other', 'Other')], max_length=255, null=True)),
                ('rejected_message', models.TextField(blank=True, null=True)),
                ('rejeted_file', models.FileField(blank=True, null=True, upload_to='rejected/')),
            ],
        ),
    ]
