# Generated by Django 6.0 on 2026-04-27 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dr_personalInfo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorpersonalinfo',
            name='rejected_file',
        ),
    ]
