# Generated by Django 6.0 on 2026-05-05 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dr_personalInfo', '0002_remove_doctorpersonalinfo_rejected_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctorpersonalinfo',
            old_name='rejeted_file',
            new_name='rejected_file',
        ),
    ]
