# Generated by Django 6.0 on 2026-04-07 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Dr_personalInfo", "0001_initial"),
    ]

    operations = []
