# Generated by Django 6.0 on 2026-04-09 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dr_personalInfo', '0004_doctorpersonalinfo_rejected_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorpersonalinfo',
            name='rejeted_file',
            field=models.FileField(blank=True, null=True, upload_to='rejected/'),
        ),
        migrations.AlterField(
            model_name='doctorpersonalinfo',
            name='rejected_reason',
            field=models.CharField(blank=True, choices=[('invalid_docs', 'Invalid Documents'), ('missing_info', 'Missing Information'), ('license_issue', 'License Issue'), ('other', 'Other')], max_length=255, null=True),
        ),
    ]
