# Generated by Django 6.0 on 2026-05-08 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminLogin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Addresses'},
        ),
    ]
