# Generated by Django 6.0 on 2026-04-29 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newRequest_activePrescription_medication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='dosage',
            field=models.CharField(default='10mg', max_length=50),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medication',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
