# Generated by Django 6.0 on 2026-05-02 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newRequest_activePrescription_medication', '0003_remove_medication_dosage_remove_pharmacy_latitude_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prescriptionrequest',
            old_name='user',
            new_name='patient',
        ),
        migrations.RemoveField(
            model_name='prescriptionrequest',
            name='delivery_type',
        ),
        migrations.AddField(
            model_name='prescriptionrequest',
            name='delivery_preference',
            field=models.CharField(choices=[('pickup', 'Pickup'), ('delivery', 'Home Delivery')], default='pickup', max_length=20),
            preserve_default=False,
        ),
    ]
