# Generated by Django 6.0 on 2026-05-02 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newRequest_activePrescription_medication', '0004_rename_user_prescriptionrequest_patient_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pharmacy',
            name='phone',
        ),
        migrations.AddField(
            model_name='medication',
            name='dosage',
            field=models.CharField(default='10mg', max_length=50),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
